### ISSUE TITLE
Please put the documentation in the elisp file as well

### ISSUE THREAD

**Issue by Trevoke** [jtkDvlp/simple-bookmarks#3]
This is what I see when browsing from the package repository, and it makes discoverability ... More difficult.

![image](https://cloud.githubusercontent.com/assets/67913/16637841/17596fc6-43b0-11e6-9445-34bfa490cbb5.png)

**Comment by jtkDvlp** [comment]
Thanks for opening the issue.

The documentation should be available within the next melpa build.

**Comment by jtkDvlp** [comment]
Now it´s included!

Some format fixes will follow.
